/**
 * Muscle/equipment mapping for exercises in the StrengthLog export.
 * [primary muscles, secondary muscles, equipment, kind]
 * kind: "w" = weighted, "b" = bodyweight (+extra weight), "c" = cardio/time
 */
type Kind = "w" | "b" | "c";
type Entry = [string[], string[], string | null, Kind];

export const ALIASES: Record<string, string> = {
  "Lat pull neutral grip": "Lat Pulldown with Neutral Grip",
  "Seated Smith Overhead Press": "Seated Smith Machine Shoulder Press",
  "Sidolyft med hantel sittandes": "Seated Dumbbell Lateral Raise",
  "Bakåtlutande sidolyft med hantlar": "Leaning Dumbbell Lateral Raise",
  "Handledscurl med kabel": "Cable Wrist Curl",
  "Maskinrodd Chest-supported": "Chest-Supported Machine Row",
  "Klättring": "Climbing",
  "Jpg rodd": "JPG Row",
};

const S = "shoulders", C = "chest", T = "triceps", B = "biceps", F = "forearms", L = "lats", MB = "middle back",
  LB = "lower back", TR = "traps", AB = "abdominals", Q = "quadriceps", H = "hamstrings", G = "glutes",
  CA = "calves", AD = "adductors", ABD = "abductors";

export const SL_MAP: Record<string, Entry> = {
  "Assault Air Bike": [[Q], [], "machine", "c"],
  BJJ: [[], [], null, "c"],
  "Back Extension": [[LB], [G, H], "body only", "b"],
  "Leaning Dumbbell Lateral Raise": [[S], [], "dumbbell", "w"],
  "Bar Dip": [[T, C], [S], "body only", "b"],
  "Bar Hang": [[F], [L], "body only", "b"],
  "Bar Muscle-Up": [[L, T], [C, S, B], "body only", "b"],
  "Barbell Curl": [[B], [F], "barbell", "w"],
  "Barbell Row": [[MB, L], [B, LB], "barbell", "w"],
  "Barbell Shrug": [[TR], [], "barbell", "w"],
  "Bayesian Curl": [[B], [], "cable", "w"],
  "Bench Press": [[C], [T, S], "barbell", "w"],
  "Box Jump": [[Q], [G, CA], "body only", "b"],
  "Bulgarian Split Squat": [[Q, G], [H], "dumbbell", "w"],
  "Cable Close-Grip Seated Row": [[MB, L], [B], "cable", "w"],
  "Cable Crossover Biceps Curl": [[B], [], "cable", "w"],
  "Cable Crunch": [[AB], [], "cable", "w"],
  "Cable Curl With Bar": [[B], [F], "cable", "w"],
  "Cable Curl With Rope": [[B], [F], "cable", "w"],
  "Cable Lateral Raise": [[S], [], "cable", "w"],
  "Cable Machine Hip Abduction": [[ABD], [G], "cable", "w"],
  "Cable Pullover": [[L], [C], "cable", "w"],
  "Cable Shrug": [[TR], [], "cable", "w"],
  "Cable Wide Grip Seated Row": [[MB, L], [S, B], "cable", "w"],
  "Cable row": [[MB, L], [B], "cable", "w"],
  "Chin-Up": [[L], [B, MB], "body only", "b"],
  "Close-Grip Lat Pulldown": [[L], [B, MB], "cable", "w"],
  Cycling: [[Q], [CA], null, "c"],
  Deadlift: [[H, G, LB], [Q, TR, F], "barbell", "w"],
  "Decline Push-Up": [[C], [T, S], "body only", "b"],
  "Drag Curls": [[B], [], "barbell", "w"],
  "Dumbbell Bulgarian Split Squat": [[Q, G], [H], "dumbbell", "w"],
  "Dumbbell Chest Fly": [[C], [S], "dumbbell", "w"],
  "Dumbbell Curl": [[B], [F], "dumbbell", "w"],
  "Dumbbell Lateral Raise": [[S], [], "dumbbell", "w"],
  "Dumbbell Lunge": [[Q, G], [H], "dumbbell", "w"],
  "Dumbbell Lying Triceps Extension": [[T], [], "dumbbell", "w"],
  "Dumbbell Preacher Curl": [[B], [], "dumbbell", "w"],
  "Dumbbell Rear Delt Row": [[S], [MB], "dumbbell", "w"],
  "Dumbbell Romanian Deadlift": [[H, G], [LB], "dumbbell", "w"],
  "Dumbbell Row": [[L, MB], [B], "dumbbell", "w"],
  "Dumbbell Shoulder Press": [[S], [T], "dumbbell", "w"],
  "EZ Curl": [[B], [F], "e-z curl bar", "w"],
  "Explosive push ups": [[C], [T, S], "body only", "b"],
  "Face Pull": [[S], [MB, TR], "cable", "w"],
  "Fluttering kick": [[AB], [], "body only", "w"],
  "French Press Cable": [[T], [], "cable", "w"],
  "French Press Dumbbell": [[T], [], "dumbbell", "w"],
  "Front Squat": [[Q], [G, AB], "barbell", "w"],
  "Glute Bridge": [[G], [H], "body only", "b"],
  HIIT: [[], [], null, "c"],
  "Hack Squat Machine": [[Q], [G], "machine", "w"],
  "Hammer Curl": [[B, F], [], "dumbbell", "w"],
  "Cable Wrist Curl": [[F], [], "cable", "w"],
  "Hanging Knee Raise": [[AB], [], "body only", "b"],
  "Hanging Leg Raise": [[AB], [F], "body only", "b"],
  "High Machine Row": [[L, MB], [B], "machine", "w"],
  "Hip Abduction Machine": [[ABD], [G], "machine", "w"],
  "Hip Adduction Machine": [[AD], [], "machine", "w"],
  "Hip Thrust Machine": [[G], [H], "machine", "w"],
  "Incline Bench Press": [[C], [S, T], "barbell", "w"],
  "Incline Cable Chest Fly": [[C], [S], "cable", "w"],
  "Incline Dumbbell Curl": [[B], [], "dumbbell", "w"],
  "Incline Dumbbell Press": [[C], [S, T], "dumbbell", "w"],
  "Incline Machine Chest Press": [[C], [S, T], "machine", "w"],
  "Incline Machine Press": [[C], [S, T], "machine", "w"],
  "Inverted Row": [[MB, L], [B], "body only", "b"],
  "JPG Row": [[MB, L], [B], "machine", "w"],
  "Kettlebell Front Squat": [[Q], [G], "kettlebells", "w"],
  "Kettlebell Jump": [[Q, G], [CA], "kettlebells", "w"],
  "Kettlebell Row": [[L, MB], [B], "kettlebells", "w"],
  "Kettlebell Swing": [[G, H], [LB, S], "kettlebells", "w"],
  Climbing: [[L, F], [B], null, "c"],
  "Kneeling Ab Wheel": [[AB], [L], "other", "b"],
  "Lat Pulldown": [[L], [B, MB], "cable", "w"],
  "Lat Pulldown With Supinated Grip": [[L], [B, MB], "cable", "w"],
  "Lat Pulldown with Neutral Grip": [[L], [B, MB], "cable", "w"],
  "Leg Extension": [[Q], [], "machine", "w"],
  "Leg Press": [[Q], [G, H], "machine", "w"],
  "Lunge (Bodyweight)": [[Q, G], [H], "body only", "b"],
  "Lying Leg Curl": [[H], [CA], "machine", "w"],
  "Lying Leg Raise": [[AB], [], "body only", "b"],
  "Lying Machine Chest Press (Plate Loaded)": [[C], [S, T], "machine", "w"],
  "Machine Chest Fly": [[C], [S], "machine", "w"],
  "Machine Chest Press": [[C], [S, T], "machine", "w"],
  "Machine Lat Pulldown": [[L], [B, MB], "machine", "w"],
  "Machine Lateral Raise": [[S], [], "machine", "w"],
  "Machine Shoulder Press": [[S], [T], "machine", "w"],
  "Chest-Supported Machine Row": [[MB, L], [B, S], "machine", "w"],
  "Nordic Hamstring": [[H], [], "body only", "b"],
  "Nordic Hamstring Eccentric": [[H], [], "body only", "b"],
  "One arm pushdown": [[T], [], "cable", "w"],
  "One-Arm Cable Row": [[L, MB], [B], "cable", "w"],
  "One-Arm Kettlebell Swing": [[G, H], [LB, S], "kettlebells", "w"],
  "One-Arm Lat Pulldown": [[L], [B], "cable", "w"],
  "Overhead Cable Triceps Extension": [[T], [], "cable", "w"],
  "Overhead Cable Triceps Extension from Upper Position": [[T], [], "cable", "w"],
  "Overhead Press": [[S], [T, TR], "barbell", "w"],
  "Pec Deck": [[C], [S], "machine", "w"],
  "Preacher Machine": [[B], [], "machine", "w"],
  "Pull-Up": [[L], [B, MB], "body only", "b"],
  Pullover: [[L], [C, T], "dumbbell", "w"],
  "Push-Up": [[C], [T, S], "body only", "b"],
  "Reverse Barbell Curl": [[F, B], [], "barbell", "w"],
  "Reverse Machine Fly": [[S], [MB, TR], "machine", "w"],
  "Reverse wrist curl": [[F], [], "dumbbell", "w"],
  "Ring Pull-Up": [[L], [B, MB], "body only", "b"],
  "Romanian Deadlift": [[H, G], [LB], "barbell", "w"],
  "Romanian kettlebell": [[H, G], [LB], "kettlebells", "w"],
  Running: [[Q], [H, CA], null, "c"],
  "Seal Row": [[MB, L], [B], "barbell", "w"],
  "Seated Dumbbell Shoulder Press": [[S], [T], "dumbbell", "w"],
  "Seated Dumbbell Lateral Raise": [[S], [], "dumbbell", "w"],
  "Seated Leg Curl": [[H], [], "machine", "w"],
  "Seated Machine Row": [[MB, L], [B], "machine", "w"],
  "Seated Smith Machine Shoulder Press": [[S], [T], "machine", "w"],
  "Single Leg Deadlift with Kettlebell": [[H, G], [LB], "kettlebells", "w"],
  "Sitting Cable Chest Fly": [[C], [S], "cable", "w"],
  "Smith Machine Incline Bench Press": [[C], [S, T], "machine", "w"],
  "Smith Machine Romanian Deadlift": [[H, G], [LB], "machine", "w"],
  "Smith Machine Squat": [[Q], [G, H], "machine", "w"],
  "Spider Curl": [[B], [], "dumbbell", "w"],
  Squat: [[Q], [G, H, LB], "barbell", "w"],
  "Standing Cable Chest Fly (Lower Position)": [[C], [S], "cable", "w"],
  "Standing Cable Chest Fly (Upper Position)": [[C], [S], "cable", "w"],
  "Standing Calf Raise": [[CA], [], "machine", "w"],
  "Standing Dumbbell Shoulder Press": [[S], [T], "dumbbell", "w"],
  "Step-Up": [[Q, G], [H], "body only", "b"],
  "T-Bar Row": [[MB, L], [B], "barbell", "w"],
  "Trap Bar Deadlift With Low Handles": [[Q, G, H], [LB, TR], "barbell", "w"],
  "Tricep Dip Machine": [[T], [C], "machine", "w"],
  "Triceps Pushdown With Bar": [[T], [], "cable", "w"],
  "Triceps Pushdown With Rope": [[T], [], "cable", "w"],
  "Y raise": [[S], [TR], "dumbbell", "w"],
  Yoga: [[], [], null, "c"],
  "Zottman Curl": [[B, F], [], "dumbbell", "w"],
};
